### YamlMime:Lifecycle
metadata:
  title: Διαχείριση ρύθμισης παραμέτρων του Microsoft System Center (LTSB-έκδοση 1606)
  description: Το Microsoft System Center Configuration Manager (LTSB-έκδοση 1606) ακολουθεί την πολιτική σταθερού κύκλου ζωής.
  ms.date: 08/20/2020
  ms.openlocfilehash: 606034d7f3694f3e06a47bdc5e1a45561102c238
  ms.sourcegitcommit: f5095aa6fc41dcc71c883cae08719b5b6bf9585c
  ms.translationtype: MT
  ms.contentlocale: el-GR
  ms.lasthandoff: 08/20/2020
  ms.locfileid: "905852"
name: Διαχείριση ρύθμισης παραμέτρων του Microsoft System Center (LTSB-έκδοση 1606)
summary: >+
  Το Microsoft System Center Configuration Manager (LTSB-έκδοση 1606) ακολουθεί την πολιτική [σταθερού](/lifecycle/policies/fixed) κύκλου ζωής.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Πληροφορίες εξυπηρέτησης και υποστήριξης](/sccm/core/understand/learn-more-editions)"
