### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: Ο Microsoft System Center Configuration Manager 2007 ακολουθεί την Πολιτική Σταθερού Κύκλου Ζωής.
  ms.date: 07/28/2020
  ms.openlocfilehash: 796670fd93547cc79f69c544085070efb0116650
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: el-GR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "818521"
name: Microsoft System Center Configuration Manager 2007
summary: "Ο Microsoft System Center Configuration Manager 2007 ακολουθεί την Πολιτική [Σταθερού](/lifecycle/policies/fixed) Κύκλου Ζωής. \n\n\n> [!IMPORTANT]\n> Η υποστήριξη για αυτό το προϊόν έληξε. Ανατρέξτε στις οδηγίες μετεγκατάστασης παρακάτω.\n"
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Service Pack 2
  startDate: 10/22/2009
  endDate: 07/09/2019
- version: Service Pack 1
  startDate: 05/21/2008
  endDate: 01/11/2011
- version: Original Release
  startDate: 11/29/2007
  endDate: 07/14/2009
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Οδηγίες Μετεγκατάστασης](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Πληροφορίες Προϊόντος](/mem/configmgr/core/understand/introduction)\n* [Πολιτική του Service Pack](/lifecycle/policies/fixed#service-packs)"
