### YamlMime:Lifecycle
metadata:
  title: Διαχείριση παραμέτρων του Κέντρου συστήματος της Microsoft 2012
  description: Η Διαχείριση ρύθμισης παραμέτρων του Κέντρου συστήματος της Microsoft 2012 ακολουθεί την πολιτική σταθερού κύκλου ζωής.
  ms.date: 07/28/2020
  ms.openlocfilehash: dce8796f280b29e070bbf1d5bab55452f6e706e7
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: el-GR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "854407"
name: Διαχείριση παραμέτρων του Κέντρου συστήματος της Microsoft 2012
summary: >+
  Η Διαχείριση ρύθμισης παραμέτρων του Κέντρου συστήματος της Microsoft 2012 ακολουθεί την πολιτική [σταθερού](/lifecycle/policies/fixed) κύκλου ζωής.


products:
- msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 2
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Service Pack 1
  startDate: 12/15/2012
  endDate: 07/12/2016
- version: Original Release
  startDate: 05/30/2012
  endDate: 01/14/2014
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Πολιτική service pack](/lifecycle/policies/fixed#service-packs)\n* [Τεκμηρίωση κέντρου συστήματος](/system-center/#pivot=components&panel=components-all)\n* [Πόροι κέντρου συστήματος](https://www.microsoft.com/system-center/resources)"
