### YamlMime:Lifecycle
metadata:
  title: Κεντρικό Σύστημα Microsoft Configuration Manager 2007 R2
  description: Η Διαχείριση Ρύθμισης Παραμέτρων του Κέντρου Συστήματος της Microsoft 2007 R2 ακολουθεί την Πολιτική Σταθερού Κύκλου Ζωής.
  ms.date: 07/28/2020
  ms.openlocfilehash: dc120aa48cf00c559b79cd24b31cde9a8122b573
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: el-GR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4106230"
name: Κεντρικό Σύστημα Microsoft Configuration Manager 2007 R2
summary: >
  Η Διαχείριση Ρύθμισης Παραμέτρων του Κέντρου Συστήματος της Microsoft 2007 R2 ακολουθεί την Πολιτική [Σταθερού](/lifecycle/policies/fixed) Κύκλου Ζωής.



  > [!IMPORTANT]

  > Η υποστήριξη για αυτό το προϊόν έληξε. Ανατρέξτε στις οδηγίες μετεγκατάστασης παρακάτω.
products:
- msc
policyType: fixed
supportDates:
  start: 2008-11-29T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2008-11-29T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Οδηγίες Μετεγκατάστασης](/mem/configmgr/core/migration/planning-for-migration)\n* [Πρόσθετες οδηγίες μετεγκατάστασης](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
