### YamlMime:Lifecycle
metadata:
  title: Κεντρικό σύστημα Microsoft 2012 Configuration Manager
  description: Η Διαχείριση Ρύθμισης Παραμέτρων του Κέντρου Συστήματος της Microsoft 2012 ακολουθεί την Πολιτική Σταθερού Κύκλου Ζωής.
  ms.date: 03/12/2021
  keywords: null
name: Κεντρικό σύστημα Microsoft 2012 Configuration Manager
summary: |+
  Η Διαχείριση Ρύθμισης Παραμέτρων του Κέντρου Συστήματος της Microsoft 2012 ακολουθεί την Πολιτική [Σταθερού](/lifecycle/policies/fixed) Κύκλου Ζωής.


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>Συνδέσεις 
  * [Πολιτική του Service Pack](/lifecycle/policies/fixed#service-packs)
  * [Κεντρικό σύστημα εγγράφων (documentation)](/system-center/#pivot=components&panel=components-all)
  * [Κεντρικό σύστημα Πόρων](https://www.microsoft.com/system-center/resources)
  * [Οδηγίες Μετεγκατάστασης](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)