### YamlMime:Lifecycle
metadata:
  title: Σύστημα Microsoft Center Configuration Manager 2007 R3
  description: Το Σύστημα Microsoft System Center Configuration Manager 2007 R3 ακολουθεί την Πολιτική Σταθερού Κύκλου Ζωής.
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: el-GR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "854621"
name: Σύστημα Microsoft Center Configuration Manager 2007 R3
summary: >
  Το Σύστημα Microsoft System Center Configuration Manager 2007 R3 ακολουθεί την Πολιτική [ Σταθερού](/lifecycle/policies/fixed) Κύκλου Ζωής.



  > [!IMPORTANT]

  > Η υποστήριξη για αυτό το προϊόν έληξε. Ανατρέξτε στις οδηγίες μετεγκατάστασης παρακάτω.
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Οδηγίες Μετεγκατάστασης](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Πρόσθετες οδηγίες μετεγκατάστασης](/mem/configmgr/core/migration/planning-for-migration)"
