### YamlMime:Lifecycle
metadata:
  title: Σουίτα εφαρμογών PixelSense 1.0
  description: Η σουίτα εφαρμογών PixelSense 1.0 ακολουθεί την Πολιτική Σταθερού Κύκλου Ζωής.
  ms.date: 08/12/2020
  ms.openlocfilehash: c74536304840d0d75306a3d6d2609d8a39c524dc
  ms.sourcegitcommit: 1974bfc9a9fccaac36daaa1015b7f31c8814ae07
  ms.translationtype: HT
  ms.contentlocale: el-GR
  ms.lasthandoff: 08/12/2020
  ms.locfileid: "892031"
name: Σουίτα εφαρμογών PixelSense 1.0
summary: >+
  Η σουίτα εφαρμογών PixelSense 1.0 ακολουθεί την Πολιτική [Σταθερού](/lifecycle/policies/fixed) Κύκλου Ζωής.


products:
- windows
policyType: fixed
supportDates:
  start: 01/01/2009
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 1
  startDate: 08/09/2009
  endDate: 01/08/2019
- version: Original Release
  startDate: 01/01/2009
  endDate: 01/08/2019
content: ''
