### YamlMime:Lifecycle
metadata:
  title: Σουίτα εφαρμογών PixelSense 1.0
  description: Το PixelSense Applications Suite 1.0 ακολουθεί την Πολιτική σταθερού κύκλου ζωής.
  ms.date: 07/28/2020
  ms.openlocfilehash: 5359b0dd917124f3b47cb74f30a3ff92657c2155
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: el-GR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "818477"
name: Σουίτα εφαρμογών PixelSense 1.0
summary: >+
  Το PixelSense Applications Suite 1.0 ακολουθεί την [Πολιτική σταθερού](/lifecycle/policies/fixed) κύκλου ζωής.


products:
- windows
policyType: fixed
supportDates:
  start: 01/01/2009
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 1
  startDate: 08/09/2009
  endDate: 01/08/2019
- version: Original Release
  startDate: 01/01/2009
  endDate: 01/14/2014
content: ''
